#!/bin/bash

rm *.o
#compile all c files
for f in `ls *.cpp`
do
	obj=`echo $f | sed -e 's/\.cpp/.o/g'`
	icpc -c  -debug  -O0 -DDEBUG -o $obj $f
	echo $f $obj
done
#link
#gcc -lm -o tablegen energy.o io.o mt.o rotations.o tablegen.o tables.o
icpc  -debug  -O0 -o tablemc-debug  *.o 

